### ISSUE TITLE
Unable to find lambda function

### ISSUE THREAD

**Issue by tupacalypse187** [geekmuse/iot-button-ec2-controller#3]
No matter what I try and I've double checked as well as copied and pasted function name from cli command 'aws lambda list-functions'. Any thoughts on why the function can't be found?
[root@antlet12 iot-button-ec2-controller]# grunt deploy
Running "lambda_package:default" (lambda_package) task
iot-button-ec2-controller@1.0.0 ../../tmp/1521421419985.6768/node_modules/iot-button-ec2-controller
└── underscore@1.8.3
Created package at ./dist/iot-button-ec2-controller_1-0-0_2018-2-18-18-3-39.zip

Running "lambda_deploy:default" (lambda_deploy) task
Warning: Unable to find lambda function arn:aws:lambda:us-west-2:570656418299:function:myButtonFunction03, verify the lambda function name and AWS region are correct. Use --force to continue.

Aborted due to warnings.

**Comment by geekmuse** [comment]
Sure the region is correct?  Can you see the function in the console?

**Comment by tupacalypse187** [comment]
Hi :)
Region in index.js matches my arn and I see the function name in the console which matches what I copy into Gruntfile.js. I'm using Oregon, which is us-west-2. I can make in us-east-1 to match your original code to see if that works. Thanks for your help and efforts in making this.

[root@antlet12 iot-button-ec2-controller]# cat index.js 
var AWS = require('aws-sdk');
var _ = require('underscore');
var ec2 = new AWS.EC2({ apiVersion: '2016-09-15' });
AWS.config.region = 'us-west-2';

**Comment by geekmuse** [comment]
Try adding the `options: { ... }` section to the `lambda_deploy` Gruntfile.

```
lambda_deploy: {
        default: {
            arn: 'arn:aws:lambda:us-west-2:570656418299:function:myButtonFunction03',
            options: {
                region: 'us-west-2'
            }
        }
    },
```

After a little more digging, it looks like this may be a [grunt-aws-lambda issue](https://github.com/Tim-B/grunt-aws-lambda/issues/73).  If it doesn't work for you by setting the option above, I'll look at re-implementing this with something that works across regions.

**Comment by tupacalypse187** [comment]
You're exactly right. Thank you.
Done, without errors.

I see from Tim-B's grunt-aws-lambda that it defaults to us-east-1 if not provided.

options.region
Type: String Default value: us-east-1

Specify the AWS region your functions will be uploaded to. Note that if an ARN is supplied this option is not required.

**Comment by geekmuse** [comment]
Good deal -- glad it worked.  I'll update the Gruntfile so the region's there starting out.

**Comment by tupacalypse187** [comment]
After pressing the button I don't get the IoT Enabled EC2 to start/stop. Where can I see the logs that show the context msg's from index.js? I'm looking in the lambda Cloudwatch log, but not showing up. Do you have a good way to test and troubleshoot? Thanks

**Comment by tupacalypse187** [comment]
When I test the lambda function using event.clickType: SINGLE/DOUBLE I get the same result. It's as if it's not able to get the instance ids.

{
  "msg": "No instances in a state to be affected by this operation.",
  "instanceIds": []
}

START RequestId: 7c733e35-2b2d-11e8-8813-fdb81cdb21c4 Version: $LATEST
2018-03-19T04:25:00.146Z	7c733e35-2b2d-11e8-8813-fdb81cdb21c4	Received event: { 'event.clickType': 'SINGLE' }
END RequestId: 7c733e35-2b2d-11e8-8813-fdb81cdb21c4
REPORT RequestId: 7c733e35-2b2d-11e8-8813-fdb81cdb21c4	Duration: 1058.74 ms	Billed Duration: 1100 ms 	Memory Size: 128 MB	Max Memory Used: 38 MB

**Comment by milvain** [comment]
Hi,

i have the same issu than @tupacalypse187 regarding 
{
"msg": "No instances in a state to be affected by this operation.",
"instanceIds": []
}

How I can fix that?
On my VM I have the tag KEY=IoT Enabled VALUE=IoT Enabled
I config on the index.js the region : AWS.config.region = 'eu-west-3';

Many thanks
