### ISSUE TITLE
Adding tag Name --> IoT Enabled does not stop/start EC2 Instance

### ISSUE THREAD

**Issue by tupacalypse187** [geekmuse/iot-button-ec2-controller#4]
Hi - Can you build out and see if all works? Maybe something has changed on AWS end. I have an EC2 instance with a tag 'Name' -> 'IoT Enabled' and pressing the button does not start or stop EC2. I also do not see any action in the logs besides SINGLE/DOUBLE. Am I labeling the tag correctly? Key = Name, Value = IoT Enabled?
All code is deployed and lambda is operationally ready. Thank you.

**Comment by tupacalypse187** [comment]
It works!! It was user error. I had to make the key = 'Iot Enabled' and the Value can be anything.

**Comment by geekmuse** [comment]
Good deal - glad you got it!
