### ISSUE TITLE
Unable to start/stop the VM

### ISSUE THREAD

**Issue by milvain** [geekmuse/iot-button-ec2-controller#5]
Hi,

i have the same issue than @tupacalypse187. When I try with a Test lambda I have: 

{
"msg": "No instances in a state to be affected by this operation.",
"instanceIds": []
}

How I can fix that?
On my VM I have the tag KEY=IoT Enabled VALUE=IoT Enabled
I config on the index.js the region : AWS.config.region = 'eu-west-3';

When I click on the button, nothing happen.

Many thanks

**Comment by geekmuse** [comment]
I can think of a few possible issues that might be going on here:

- Are the EC2 instances you want to start/stop actually located in `eu-west-3`?  `AWS.config.region` should be where the instances are, not necessarily the region the Lambda is deployed to.
- Are you sure there's not a typo on tag key?
- If you're sure the first two aren't an issue, how many EC2 instances do you have running in `eu-west-3`?  It may be that there are too many running instances for the set returned in the API call to contain references to the instances you want to act on.  I'll have a look at refactoring the function to recursively query all the EC2 instances in accounts where the EC2 footprint is substantial.

**Comment by geekmuse** [comment]
Actually, the third point above would likely be moot.  The `Filter` expression is going to limit the API response to only instances containing the tag-key, since you're showing an empty set, that's certainly not the case here.

**Comment by milvain** [comment]
Hi,
1) Yes my Lambda function is located to eu-west-1 and my EC2 instance is located to eu-west-3 so I configure AWS.config.region = 'eu-west-3'
2) I double check and I try to switch to another tag-key and I have the same issue
3) only one EC2 instance

**Comment by milvain** [comment]
For your information during the npm install

C:\Users\xxxxxx>>npm install
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 295 packages from 592 contributors and audited 1028 packages in 41.628s
found 69 vulnerabilities (9 low, 49 moderate, 11 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\xxxxxx>grunt deploy
Running "lambda_package:default" (lambda_package) task
iot-button-ec2-controller@1.0.0 ..\..\..\..\..\xxxxx\AppData\Local\Temp\xxxxxxx\node_modules\iot-button-ec2-controller
└── underscore@1.9.1
Created package at ./dist/iot-button-ec2-controller_1-0-0_2019-2-1-10-32-47.zip

Running "lambda_deploy:default" (lambda_deploy) task
Uploading...
Package deployed.
No config updates to make.

Done, without errors.

**Comment by milvain** [comment]
Lambda function:

var AWS = require('aws-sdk');
var _ = require('underscore');
var ec2 = new AWS.EC2({ apiVersion: '2016-09-15' });
AWS.config.region = 'eu-west-3';

exports.handler = (event, context, callback) => {
    console.log('Received event:', event);
    var r;
    var i;
    var instanceIds = [];

    var params = {
        Filters: [{
                Name: 'tag-key',
                Values: [
                    'IOT'
                ]
            },
        ]
    };

    ec2.describeInstances(params, function(err, data) {
        if (err) {
            console.log(err, err.stack); // an error occurred
            context.fail('Error occurred.  Aborting.');
            return;
        }

        if (data.Reservations.length) {
            for (r in data.Reservations) {
                if (data.Reservations[r].Instances.length) {
                    for (i in data.Reservations[r].Instances) {
                        if (event.clickType === 'SINGLE') {
                            if (!_.contains(['running', 'pending'], data.Reservations[r].Instances[i].State.Name)) {
                                instanceIds.push(data.Reservations[r].Instances[i].InstanceId);
                            }
                        } else if (event.clickType === 'DOUBLE') {
                            if (!_.contains(['shutting-down', 'terminated', 'stopped', 'stopping'], data.Reservations[r].Instances[i].State.Name)) {
                                instanceIds.push(data.Reservations[r].Instances[i].InstanceId);
                            }
                        }
                    }
                }
            }
        }

        i = '';
        if (instanceIds.length) {
            if (event.clickType === 'SINGLE') {
                ec2.startInstances({ InstanceIds: instanceIds }, function(err, data) {
                    if (!err) {
                        context.succeed({'msg': 'All affected instances started successfully.', 'instanceIds': instanceIds});
                    } else {
                        console.log(err, err.stack);
                        context.fail({'msg': 'Instances failed to start.', 'instanceIds': instanceIds});
                    }
                });
            } else if (event.clickType === 'DOUBLE') {
                ec2.stopInstances({ InstanceIds: instanceIds }, function(err, data) {
                    if (!err) {
                        context.succeed({'msg': 'All affected instances stopped successfully.', 'instanceIds': instanceIds});
                    } else {
                        console.log(err, err.stack);
                        context.fail({'msg': 'Instances failed to stop.', 'instanceIds': instanceIds});
                    }
                });
            }
        } else {
            context.succeed({'msg': 'No instances in a state to be affected by this operation.', 'instanceIds': instanceIds});
        }
    });

};

**Comment by milvain** [comment]
![image](https://user-images.githubusercontent.com/42184563/53645745-d83a1b80-3c39-11e9-8d2f-7568f3c11dec.png)

**Comment by geekmuse** [comment]
@milvain Try redeploying with the updated index.js (I updated the dependencies in package.json as well, but I'm going to assume you have pretty recent versions of the dependencies if you've just started playing around with this).   

https://github.com/geekmuse/iot-button-ec2-controller/releases/tag/v1.1.0

**Comment by milvain** [comment]
Many thanks @geekmuse it works now!!!!!
